<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://Papyrus/AcsProfile" nsPrefix="AcsProfile">
  <eClassifiers xsi:type="ecore:EClass" name="LinkHolder">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Link Holder"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Only purpose is to allow &quot;Link Hubs&quot; to exist inside a Composite/SoI instead of only on the boundaries of containers."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionTransition">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Action Transition"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="==Use &quot;name&quot; as an invocation/action==&#xD;&#xA;While Action Transitions and Invocation Transitions relate to Tokens, Ports, Events, Machines, Functions, Fields in table-based data types, and Declared types (and indirectly more), this has proven both non-user-friendly and overly complex to model explicitly. Thus, actions and invocations are simply represented as strings through the &quot;name&quot; property, since this is visible in a UML diagram."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationTransition">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Invocation Transition"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="==Use &quot;name&quot; as an invocation/action==&#xD;&#xA;While Action Transitions and Invocation Transitions relate to Tokens, Ports, Events, Machines, Functions, Fields in table-based data types, and Declared types (and indirectly more), this has proven both non-user-friendly and overly complex to model explicitly. Thus, actions and invocations are simply represented as strings through the &quot;name&quot; property, since this is visible in a UML diagram."/>
    </eAnnotations>
    <eOperations name="Noncycliclocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Non-cyclic (local)"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="not (self.end_state = self.start_state)"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//Subsystem #//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem" abstract="true" eSuperTypes="#//System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinality" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicSystem" eSuperTypes="#//Subsystem">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Atomic System"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkConnection">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Link Connection"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Directionality" ordered="false"
        lowerBound="1" eType="#//ConnectionTypes" defaultValueLiteral="reactive"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinality" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionTypes">
    <eLiterals name="reactive"/>
    <eLiterals name="active" value="1"/>
    <eLiterals name="self_referential" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoI" eSuperTypes="#//System #//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Subsystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced_soi" ordered="false"
        lowerBound="1" eType="#//SoI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConnection">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Interface Connection"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventDeclaration" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_StateMachine" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_StateMachine" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainMachine" eSuperTypes="#//ExplicitMachine">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Main Machine"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out_typs" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Full_Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out_toks" ordered="false"
        upperBound="-1" eType="#//TokenType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in_toks" ordered="false"
        upperBound="-1" eType="#//TokenType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link_hub" ordered="false"
        lowerBound="1" eType="#//LinkHub"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitMachine" abstract="true" eSuperTypes="#//Machine">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Explicit Machine"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="func_decls" ordered="false"
        upperBound="-1" eType="#//FuncDecl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Region" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncDecl" eSuperTypes="#//TypInOut">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Func Decl"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypInOut" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="out_typs" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Full_Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in_typs" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Full_Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Full_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="TokenType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IsGroup" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsystem" ordered="false"
        lowerBound="1" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkHub">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Link Hub"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initiator" eSuperTypes="#//TypInOut #//EventDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Handler" eSuperTypes="#//TypInOut #//EventDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber" eSuperTypes="#//EventDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="out_typs" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Full_Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//EventDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="in_typs" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Full_Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubMachine" eSuperTypes="#//ExplicitMachine #//TypInOut">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Sub Machine"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerBody">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Controller Body"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Region" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Region"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMState" abstract="true">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="COM State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CONState" abstract="true">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="CON State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tokens" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Lockable" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitMachine" eSuperTypes="#//Machine">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Implicit Machine"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CONIntermediateState" eSuperTypes="#//CONState">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="CON Intermediate State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMIntermediateState" eSuperTypes="#//COMState">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="COM Intermediate State"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CONStartState" eSuperTypes="#//CONState">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="CON Start State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Pseudostate" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Pseudostate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMStartState" eSuperTypes="#//COMState">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="COM Start State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InVars" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InToks" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Pseudostate" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Pseudostate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COMEndState" eSuperTypes="#//COMState">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="COM End State"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OutVars" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_FinalState" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//FinalState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out_toks" ordered="false"
        upperBound="-1" eType="#//TokenSelector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TokenSelector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SelectAll" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false" lowerBound="1"
        eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declared_Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//ACS_Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ACS_Type" eSuperTypes="#//Full_Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structure" ordered="false"
        lowerBound="1" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" ordered="false"
        upperBound="-1" eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eOperations name="Onlyonestructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Only one structure"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="let seq = Sequence { self.symbol->notEmpty(), self.table->notEmpty(), self.dimension->notEmpty(), self.nullable->notEmpty(), not (self.primitive_type = NONE), self.type_reference->notEmpty() } in&#xD;&#xA;&#x9;seq->count(true)->size() = 1"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type_reference" ordered="false"
        eType="#//Type_Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fundamental_type" ordered="false"
        eType="#//Fundamental_Types"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nullable" ordered="false"
        eType="#//Nullable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" ordered="false"
        eType="#//Enumeration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" ordered="false"
        eType="#//Array" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" ordered="false"
        eType="#//Record" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type_Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenced_type" ordered="false"
        lowerBound="1" eType="#//Declared_Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fundamental_Types">
    <eLiterals name="char"/>
    <eLiterals name="num" value="1"/>
    <eLiterals name="bool" value="2"/>
    <eLiterals name="NONE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nullable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nullable_base" ordered="false"
        lowerBound="1" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration">
    <eOperations name="Noduplicatenames" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="No duplicate names"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.Elements->asBag()->size() = self.Elements->asSet()->size()"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Elements" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension_base" ordered="false"
        lowerBound="1" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record">
    <eOperations name="BasetypeisRecord" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Base type is Record"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="if self.table_base->notEmpty()then&#xD;&#xA;&#x9;self.table_base.referenced_type.type.structure->oclIsTypeOf(Record)&#xD;&#xA;else&#xD;&#xA;&#x9;true&#xD;&#xA;endif"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="Noduplicatefields" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="No duplicate fields"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="let names = self.fields->collect(f : Field | f.FieldName) in&#xD;&#xA;&#x9;names->size() = names->asSet()->size()"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table_base" ordered="false"
        eType="#//Type_Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FieldName" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral="field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field_type" ordered="false"
        lowerBound="1" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" ordered="false" upperBound="-1"
        eType="#//Path" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
        lowerBound="1" eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eOperations name="Onlyonepath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Only one path"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="let seq = Sequence { self.fieldpath->notEmpty(), self.basepath->notEmpty(), self.elementpath->notEmpty() } in&#xD;&#xA;&#x9;seq->count(true)->size() = 1"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldpath" ordered="false"
        eType="#//FieldPath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basepath" ordered="false"
        eType="#//BasePath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementpath" ordered="false"
        eType="#//ElementPath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldPath">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Field" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasePath"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementPath"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eOperations name="Onlyoneproperty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Only one property"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="let seq = Sequence { self.precision->notEmpty(), self.num_range->notEmpty(), self.char_range->notEmpty(), self.symbol_range->notEmpty(), self.array_size_range->notEmpty() } in&#xD;&#xA;&#x9;seq->count(true)->size() = 1"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol_range" ordered="false"
        eType="#//SymbolRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precision" ordered="false"
        eType="#//Precision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="num_range" ordered="false"
        eType="#//NumRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="char_range" ordered="false"
        eType="#//CharRange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="array_size_range" ordered="false"
        eType="#//ArraySizeRange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymbolRange">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Symbol Range"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Elements" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Precision">
    <eOperations name="Nonnegative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Non-negative"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.Precision >= 0"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precision" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumRange">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Num Range"/>
    </eAnnotations>
    <eOperations name="Propernumrange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Proper num range"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.Min &lt;= self.Max"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Min" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Max" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharRange">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Char Range"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CharGroupRegex" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArraySizeRange">
    <eOperations name="Propersizerange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Proper size range"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="self.Min &lt;= self.Max"/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Min" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//UnlimitedNatural"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Max" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//UnlimitedNatural"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Full_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ACS_Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
        eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" ordered="false"
        upperBound="-1" eType="#//SoI"/>
  </eClassifiers>
</ecore:EPackage>
